spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: telus-service-route
          uri: ${USER_SERVICE_URI} #http://telus-service.default.svc.cluster.local:7878 #http://34.123.220.19:80 #uri: ${USER_SERVICE_URI} #http://localhost:7878  # lb://telus-service (from K8s service)
          predicates:
            - Path=/telus-service/auth/**,/telus-service/integration/**
          filters:
            - StripPrefix=1
     #   - id: note-app
     #     uri: ${NOTE_APP_URI}  # lb://noteapp-service (from K8s service)
     #     predicates:
      #      - Path=/notes/**
     #     filters:
      #      - StripPrefix=1

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

logging:
  level:
    com.sm.noteApp: TRACE
    reactor.netty.http.client: TRACE
    org.springframework.web.reactive: TRACE
    org.springframework.cloud.gateway: TRACE
