logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    com:
      sm:
        noteApp: trace

spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: http://user-service-svc:8081
          #          uri: http://34.118.239.46:8081
          predicates:
            - Path=/auth/**,/integration/**
        - id: note-app
          uri: http://noteapp-service-svc:8082
          #          uri: http://34.118.238.43:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0


#server:
#  port: 8080
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *