spring:
  application:
    name: ApiGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      #      discovery:
      #        locator:
      #          enabled: true
      routes:
        - id: user-service
          #          uri: lb://user-service-svc
          uri: http://localhost:9090
          predicates:
            - Path=/auth/**,/integration/**
        - id: note-app
          uri: http://localhost:8082
          #          uri: lb://noteapp-service-svc
          predicates:
            - Path=/api/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings

logging:
  level:
    com:
      sm:
        noteApp: TRACE
    reactor:
      netty:
        http:
          client: TRACE
    org:
      springframework:
        web:
          reactive: TRACE
        cloud:
          gateway: TRACE