spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:9090
          predicates:
            - Path=/integration/**
        - id: note-app
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0
server:
  port: 8080
