spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service-svc
#          uri: http://34.118.239.46:8081
          predicates:
            - Path=/auth/**,/integration/**
        - id: note-app
          uri: lb://noteapp-service-svc
#          uri: http://34.118.238.43:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=0
#server:
#  port: 8080
