name: github action demo build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ultimate-flare-452110-g3
  GKE_CLUSTER: cluster-demo-1    # TODO: update to cluster name
  GKE_ZONE: us-central1-c   # TODO: update to cluster zone


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Echo Build Successful
        run: echo "Build was successful!"

      # Authenticate with Google Cloud using service account key
      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Add your GCP service account key as a secret in GitHub


      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Echo Build Successful
        run: echo "Build was successful!"
      
      # Build & push Docker image (corrected section)
      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ultimate-flare-452110-g3/apigateway
          tags: 0.0.2
          dockerfile: ./Dockerfile  # Ensure the correct relative path to the Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io  # Set registry here within the `with` block
